devinea/mvx19-cms

src/components/guideline-header/guideline-header.js
src/components/guideline-left-nav/guideline-left-nav.js
src/pages/design/guidelines.js
src/templates/blog-post/blog-post.js

https://github.wdf.sap.corp/gd/FioriExperience/issues/119

Do controls graphQL query in the left Nav component instead of the page.

---

src/components/search/search.js
src/pages/index.js

There were a few errors in console. Should be ok now

Bugfix/console errors-warnings

---

src/pages/blog/2019-01-14-new-sketch-plugin-announced.md

Revert "Update Blog “2019-01-14-new-sketch-plugin-announced”"

---

.gitignore

No need to have cypress video or screenshots in the repo

gitignore for cypress items from test runs

---

src/pages/guideline_android/2019-02-6-foundation.md
src/pages/guideline_ios/2019-02-6-foundation.md
src/templates/android-guideline-post/android-guideline-post.js
src/templates/ios-guideline-post/ios-guideline-post.js
static/admin/config.yml

https://github.wdf.sap.corp/gd/FioriExperience/issues/170

Add IOS and Android collections with some defaults

---

src/components/Card/Card.js
src/components/Description/Description.js
src/components/Hamburger/Button/HamburgerButton.js
src/components/Hamburger/Menu/HamburgerMenu.js
src/components/Hamburger/Menu/InternalMenuLink.js
src/components/LayoutFooter/ExternalFooterLink.js
src/components/LayoutFooter/Footer.js
src/components/LayoutFooter/FooterLink.js
src/components/LayoutHeader/HeaderLink.js
src/components/SearchNew/Button/SearchButton.js
src/components/SearchNew/Input/SearchInput.js
src/components/theme.js
src/pages/getstarted/DescriptionList.js
src/pages/getstarted/GetStarted.js
src/pages/getstarted/ResourcesList.js

Fix the colour palette after getting it from @i849443

fix the color palette

---

src/components/LayoutFooter/ExternalFooterLink.js
src/components/LayoutFooter/Footer.js
src/components/LayoutFooter/FooterLink.js
src/components/LayoutHeader/HeaderLink.js

fix colors for header and footer

---

src/components/Card/Card.js
src/components/SearchNew/Input/SearchInput.js
src/pages/getstarted/DescriptionList.js
src/pages/getstarted/GetStarted.js
src/pages/getstarted/ResourcesList.js

fix some layout on search & getstarted

fix some layout on search & getstarted

---

package.json
src/components/Card/Card.js
src/components/Layout/Layout.js
src/components/LayoutHeader/Header.js
src/components/SearchNew/Button/SearchButton.js
src/components/SearchNew/Input/SearchInput.js
src/components/search/search.js
src/pages/search/Search.js
src/pages/search/index.js

Add a search page. No styling done on the result page as we have no design yet.
The basic search is there.

add a search page

---

src/components/LayoutFooter/ExternalFooterLink.js
src/components/LayoutFooter/Footer.js
src/components/LayoutHeader/Header.js

fix following ui review from PAL

fix following ui review from PAL

---

src/components/Layout/Layout.js
src/components/LayoutHeader/Header.js

fix the header/search following comments

fix the header/search following comments

---

src/cms/cms.js
static/admin/config.yml

Added default guideline template for guidelines markdown https://github.wdf.sap.corp/gd/FioriExperience/issues/189

TBI/Template for guideline content#189

---

src/components/Description/Description.js
src/pages/getstarted/DescriptionList.js

fix the fonts on the getstarted page

fix the fonts on the getstarted page

---

src/components/LayoutHeader/Header.js
src/components/SearchNew/Button/SearchButton.js

hide the search icon when the hamburger menu is on

hide the search icon when the hamburger menu is on

---

src/components/Filter/Filter.js
src/pages/designguideline/1-02-button.md
src/pages/designguideline/1-02-input-field.md
src/pages/designguideline/1-03-button.md
src/pages/designguideline/1-03-controls.md
src/pages/designguideline/1-03-foundation.md
src/templates/design-guideline-post/design-guideline-post.js

Fix the bug in version dropdown behaviour 
Added more version for testing

Fix version dropdown flow

---

src/components/Layout/Layout.js
src/components/LayoutHeader/Header.js
src/components/LayoutHeader/HeaderLink.js

always display the shadow on header
remove the 2 pixel white space between header link underline and header bottom border

always display the shadow on header

---

src/components/LeftNav/LeftNav.js
src/components/LeftNav/LeftNavLink.js
src/pages/guideline/android/index.js
src/pages/guideline/cux/index.js
src/pages/guideline/ios/index.js
src/pages/guideline/web/index.js
src/templates/web-guideline-post/web-guideline-post.js

Update left hand navigation to support new data structure. The title for each section is now included in the data.

Left Nav update for new data structure.

---

src/components/LayoutHeader/Header.js
src/components/LeftNav/LeftNav.js
src/templates/web-guideline-post/web-guideline-post.js

Contains the following changes after Dublin Designer review:
- Main content no longer shrinks when menu is opening/closing
- Can only open/close LHS menu when screen size is below large desktop
- LHS menu now slide in from the left rather than clipped as previously.
- Updated z-index of header and LHS nav to accommodate main content.

UX review changes to Left hand nav

---

src/components/LeftNav/LeftNav.js
src/components/LeftNav/LeftNavLink.js

Further review changes with designers:
- Fade close icon
- Pointer cursor on menu item with children
- re-open menu icon slides in from left after delay.

Further left nav review changes

---

gatsby-config.js
src/pages/versions/android-version.json
src/pages/versions/cux-version.json
src/pages/versions/ios-version.json
src/pages/versions/web-version.json
static/admin/config.yml

Add version Collection for  https://github.wdf.sap.corp/gd/FioriExperience/issues/196

Add version collection

---

src/components/LeftNav/LeftNav.js
static/img/icons/ico-sidebar_24x24.svg

After further discussion with Goran, updating open LHS menu div to be 34px x 34px, and new more rounded SVG icon.

Further LHS Nav UX updates

---

src/components/Dropdown/Dropdown.js
src/components/Panel/Panel.js
src/pages/guideline/ios/index.js

https://github.wdf.sap.corp/gd/FioriExperience/issues/175

Feature/ios-page-175 Mobile view + Desktop UX review comments
